### ISSUE TITLE
BS 4 - Pläne für die Zukunft

### ISSUE THREAD

**Issue by Olli** [contao-bootstrap/core#12]
Hi,
wie sehen eigentlich die Pläne für Bootstrap 4 aus?

**Comment by dmolineus** [comment]
Grundsätzlich würde ich gerne die Erweiterung auch für Bootstrap 4 fit machen. Noch ist allerdings nicht abzusehen, wann Bootstrap 4 erscheinen wird. Zwischen Alpha 1 und 2 gab es ja noch deutliche Änderungen. Solange es keine RC hat, werde ich nicht an einer konkreten Umsetzung arbeiten.

Eine Option wäre eine komplett überarbeitete Version nur für Contao 4. Dies hängt aber stark davon ab, ab wann Contao 4 für die breite Masse einsatzfähig wird.

**Comment by dmolineus** [comment]
Geschlossen, da abhängig von contao-bootstrap/bundle#2
