### ISSUE TITLE
Bootstrap-Konfiguration für Themes abschaltbar

### ISSUE THREAD

**Issue by zonky2** [contao-bootstrap/core#17]
Wird contao-bootstrap installiert, werden automatisch bestimmte JS- und CSS-Sachen im Template geladen - bei einer Multi-Domain-Installation kann es dabei zu unschönen Effekten kommen

Daher wäre es schön, wenn BS im Backend für Themes und für Formulare abschaltbar wäre.

**Comment by dmolineus** [comment]
Soweit wie möglich wird dies über die Auswahl des Layouttyps (Standard oder Bootstrap) bereits geregelt. Allerdings gibt es einige Sachen, die sich nicht dynamisch ändern lassen (angepasste Templates). Daher gibt es leider einige Überschneidungen. 

Für den Fall einer Multidomaininstallation müsste man dann sicherstellen, dass im Templateordner eines Themes der Nicht-Bootstrap-Installation dann die Standardtemplates vorhanden sind.

**Comment by zonky2** [comment]
Ich habe in einer Multidomain-Installation ein Theme mit "Bootstrap-Layouts" und ein Theme mit "Contao-Standard-Layouts"

In den allgemeinen Einstellungen für die Subcolumns kann nur Global eine Einstellung gemacht werden - wird hier die BS-Variante ausgewählt, werden auch in dem Standard-Layout BS-Teile geladen und (in meinem Fall) einiges im CSS zerschossen.

Aktuell musste ich es so lösen, dass Standard auf YAML steht und ich in der initconfig
```
if($_SERVER['SERVER_NAME'] == 'spezial-bs.my-domain.de') {
    $GLOBALS['TL_CONFIG']['subcolumns'] = 'bootstrap_customizable';
}
```
die Sache abfange - man muss sich dann um an die Einstellungen im BE zu gelangen auch in der Subdomain anmelden.

**Comment by dmolineus** [comment]
Das Problem hier ist die Limitierung von Subcolumns. Dieses erlaubt es nicht die Einstellung Theme-Unabhängig vorzunehmen. In v2 erübrigt sich dies, da nicht mehr auf Subcolumns aufgebaut werden wird.

**Comment by zonky2** [comment]
was wird statt subcolumns kommen?

**Comment by dmolineus** [comment]
> was wird statt subcolumns kommen?

https://github.com/contao-bootstrap/grid
