### ISSUE TITLE
contao_bootstrap.core.dca.wrapper

### ISSUE THREAD

**Issue by csaeum** [contao-bootstrap/core#19]
Ich nutze gerade die Version dev-contao4#292b96e8

Internal Server Error
Was ist das Problem?

Attempted to load class "contao_bootstrap.core.dca.wrapper" from the global namespace. Did you forget a "use" statement?

Dies kommt wenn ich einen Artikel bearbeiten will.

**Comment by dmolineus** [comment]
Fixed in the meanwhile (See 9b3f72ac72d999b528684a2a3730f98b1399f1df) and alpha2 released.
