### ISSUE TITLE
Link in the extension easy_themes not working

### ISSUE THREAD

**Issue by netzarbeiter** [contao-bootstrap/core#20]
https://github.com/contao-bootstrap/core/blob/8fd3982fa3c7e46bde30e6bb13dc5a85a85230fb/module/config/config.php#L44

Change `tl_bootstrap_config` to `tl_bs_grid`.

**Comment by Seefahrer** [comment]
to make the extension work in Contao 4.4.x, a.m. bugfix needs to be applied to fllwg file:
vendor/contao-bootstrap/core/src/Resources/contao/config/config.php

**Comment by dmolineus** [comment]
The configuration system got simplified. Some settings will stay available in the theme settings. Others got dropped.
