### ISSUE TITLE
Contao 4: Update auf 4.4.5 führt zum Fehler im Bootstrap Core

### ISSUE THREAD

**Issue by wiphi** [contao-bootstrap/core#22]
Hallo, ich habe mir eine Testumgebung für Bootstrap und Contao 4 eingerichtet. Heute wollte ich die Contao 4 Management Edition auf 4.4.5 via Composer aktualisieren. Dabei kam es zu folgendem Fehler während:

Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception

```
[RuntimeException]
An error occurred while executing the "contao:install-web-dir" command: PHP Fatal error:

Fatal error: Uncaught TypeError: Return value of ContaoBootstrap\Core\DependencyInjection\ConfigPass::setConfigTypesArgument() must be an instance of ContaoBootstrap\Core\DependencyInjection\void, none returned in vendor/contao-bootstrap/core/src/DependencyInjection/ConfigPass.php:71 Stack trace: 
#0 vendor/contao-bootstrap/core/src/DependencyInjection/ConfigPass.php(34): ContaoBootstrap\Core\DependencyInjection\ConfigPass->setConfigTypesArgument(Object(Contao\ManagerPlugin\Config\ContainerBuilder)) 
#1 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(143): ContaoBootstrap\Core\DependencyInjection\ConfigPass->process(Object(Contao\ManagerPlugin\Config\ContainerBuilder)) 
#2 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(746): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object in vendor/contao-bootstrap/core/src/DependencyInjection/ConfigPass.php on line 71
```
Vielen Dank für die super Extension!

Edit: Das Problem betrifft scheinbar alle Vorgänge mit Composer. Selbst bei eine Neuinstallation kommt der Fehler. Scheinbar ist im DI Container wohl der `contao_bootstrap.config.type_manager` Service nicht registriert...

**Comment by dmolineus** [comment]
Ich bin gerade dabei die Abhängigkeit auf PHP 7.1 umzustellen. Der Core hatte in Alpha 2.0.0-alpha4 leider noch die Abhängigkeit zu PHP 7.0 drin stehen. Dadurch wurde dieser installiert, obwohl nicht kompatibel.

Ich habe den Tag 2.0.0-alpha4 nun gelöscht und 2.0.0-alpha5 released.

Zur Lösung deines Problems:
 - Sobald Packagist die Entfernung des Releases übernommen hat, sollte alpha3 installiert werden
 - Am besten aktualisierst du auf PHP 7.1

**Comment by wiphi** [comment]
Okay, Composer lässt das gerade durchlaufen. Bin gespannt. 
Ich habe gerade ein Projekt am Start, wo ich in Ruhe Contao 4 in Verbindung mit Bootstrap testen kann. Ich hab gestern versucht den Fehler im Code zu finden, doch irgendwann war auch mal die Luft raus ;).
Leider kann ich derzeit auf meinem Live-System kein PHP 7.1 installieren. Dann werde ich erstmal auf die alpha3 zurückgreifen. Auf meinem dev-System kann ich es später vielleicht einmal durchspielen.

Bedeutet das, dass Contao-Bootstrap definitiv **nicht** kompatibel zu PHP 7.0 sein wird?

Vielen Dank für die Hilfe & die super Extension!

**Comment by dmolineus** [comment]
> Bedeutet das, dass Contao-Bootstrap definitiv nicht kompatibel zu PHP 7.0 sein wird?

Ja, aufgrund des langen Supportzeitraums der 4.4 LTS, augrund der Anforderung von Contao 4.5 (auch PHP 7.1) und aufgrund der Tatsache, dass die PHP 7.0 Strict Types erst ab PHP 7.1 richtig Sinn ergeben, haben zu der Entscheidugn geführt.
