### ISSUE TITLE
Could not find package contao-bootstrap/core~2.0@beta

### ISSUE THREAD

**Issue by ArturJo** [contao-bootstrap/core#23]
Beim Ausführen der folgenden Zeile:
**composer require contao-bootstrap/core~2.0@beta**

erhalte die folgende Fehlermeldung:

**[InvalidArgumentException]
  Could not find package contao-bootstrap/core~2.0@beta at any version for your minimum-stability (beta). Check the package spelling or your minimum-stability**

Was mache ich falsch?

**Comment by dmolineus** [comment]
PHP 7.1 steht nicht zur Verfügung

**Comment by dmolineus** [comment]
Okay, typischerweise ist es der PHP 7.1 Fehler. Bei dir fehlt allerdings ein Doppelpunkt. Richtig ist:

`composer require contao-bootstrap/core:~2.0@beta`
