### ISSUE TITLE
Grid content-element erstellt <div class="">

### ISSUE THREAD

**Issue by akroii** [contao-bootstrap/core#24]
Ich verwende Contao 4.4 Managed Edition + contao-bootstrap/grid 2.0.0-beta2
Wenn ich dort im Artikel ein "Grid Start Element" anlege, legt er mir verschiedene Separatoren an. Soweit so gut.
Nur legt er im ersten Separator ein bezugsloses `<div class=""></div>` an.

Contao Backend:
![bildschirmfoto 2017-12-05 um 10 17 26](https://user-images.githubusercontent.com/8830861/33599328-1be997f4-d9a6-11e7-8793-b5b4a7540d40.png)

HTML Output
![bildschirmfoto 2017-12-05 um 10 17 03](https://user-images.githubusercontent.com/8830861/33599334-221e84f4-d9a6-11e7-906b-6e52fc2ada63.png)

**Comment by dmolineus** [comment]
Der Aufbau ist falsch. Der erste Separator wird nicht benötigt. Stimmt das Markup, wenn dieser entfernt wird?

**Comment by dmolineus** [comment]
Closed due to missing response. If the issue still occurs please open an issue at https://github.com/contao-bootstrap/grid
