### ISSUE TITLE
stable version

### ISSUE THREAD

**Issue by MDevster** [contao-bootstrap/core#25]
Hi guys,

is there a plan when the new version will leave the beta status?
We have already used the extension on some installations and have not encountered any problems so far. If you need help somewhere, just let me know.

We would like to provide a new Contao Theme for Christmas, where we use your extension. Unfortunately, then every user would have to downgrade the stability to install the theme.

Thank you for your work
regards

**Comment by dmolineus** [comment]
Next release is planned in January 2018. I wanted to release a release candidate but maybe I'll go for a stable release.

One thing that is still missing and I'd love to have for a stable version is a showcase where all components are in action with some screenshots of the backend configuration (like the components part of the current project website). If you're able to set it up and contribute it to the project it would be a great help.

**Comment by MDevster** [comment]
We would like to help with the creation of the new showcase. Is there a special repository for project website or should it be done directly in Contao?

**Comment by dmolineus** [comment]
> We would like to help with the creation of the new showcase. Is there a special repository for project website or should it be done directly in Contao?

Great. A simple Contao instance would be enough. What I'd like to have in such showcase:

- Samples for each component and it's modules/ces
- No or only really required additional modules

All the stuff which is currently on the website (blog, support, etc.) should not be part of a new showcase as it will be part of my own website soon.

**Comment by dmolineus** [comment]
Since Bootstrap 4 beta 3 no more breaking changes were promised. So there's no reason to hold a stable version back. I released it today.

**Comment by dmolineus** [comment]
> We would like to help with the creation of the new showcase. Is there a special repository for project website or should it be done directly in Contao?

@MDevster Any news about that?
