### ISSUE TITLE
Installation mit 4.10

### ISSUE THREAD

**Issue by cgpro** [contao-bootstrap/core#32]
Hi,

habe gerade versucht das aktuelle Release via Composer zu installieren:
composer require contao-bootstrap/bundle:~2.1.0 -o

Leider bekomme ich im Anschluss folgende Fehlermeldung:
`
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install contao-bootstrap/bundle 2.1.1
    - Conclusion: remove doctrine/doctrine-bundle 2.1.2
    - Installation request for contao-bootstrap/bundle ~2.1.0 -> satisfiable by contao-bootstrap/bundle[2.1.0, 2.1.1].
    - Conclusion: don't install doctrine/doctrine-bundle 2.1.2
    - contao-bootstrap/bundle 2.1.0 requires contao-bootstrap/core ~2.0 -> satisfiable by contao-bootstrap/core[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - contao-bootstrap/core 2.0.0 requires doctrine/doctrine-bundle ~1.6 -> satisfiable by doctrine/doctrine-bundle[1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.12.1, 1.12.10, 1.12.2, 1.12.3, 1.12.4, 1.12.5, 1.12.6, 1.12.7, 1.12.8, 1.12.9, 1.6.0, 1.6.1, 1.6.10, 1.6.11, 1.6.12, 1.6.13, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.9.0, 1.9.1].
    - contao-bootstrap/core 2.0.1 requires doctrine/doctrine-bundle ~1.6 -> satisfiable by doctrine/doctrine-bundle[1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.12.1, 1.12.10, 1.12.2, 1.12.3, 1.12.4, 1.12.5, 1.12.6, 1.12.7, 1.12.8, 1.12.9, 1.6.0, 1.6.1, 1.6.10, 1.6.11, 1.6.12, 1.6.13, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.9.0, 1.9.1].
    - contao-bootstrap/core 2.0.2 requires doctrine/doctrine-bundle ~1.6 -> satisfiable by doctrine/doctrine-bundle[1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.12.1, 1.12.10, 1.12.2, 1.12.3, 1.12.4, 1.12.5, 1.12.6, 1.12.7, 1.12.8, 1.12.9, 1.6.0, 1.6.1, 1.6.10, 1.6.11, 1.6.12, 1.6.13, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.9.0, 1.9.1].
    - contao-bootstrap/core 2.0.3 requires doctrine/doctrine-bundle ~1.6 -> satisfiable by doctrine/doctrine-bundle[1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.12.1, 1.12.10, 1.12.2, 1.12.3, 1.12.4, 1.12.5, 1.12.6, 1.12.7, 1.12.8, 1.12.9, 1.6.0, 1.6.1, 1.6.10, 1.6.11, 1.6.12, 1.6.13, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.9.0, 1.9.1].
    - Can only install one of: doctrine/doctrine-bundle[1.10.0, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.10.1, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.10.2, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.10.3, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.11.0, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.11.1, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.11.2, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.0, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.1, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.10, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.2, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.3, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.4, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.5, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.6, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.7, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.8, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.9, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.8.0, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.8.1, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.9.0, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.9.1, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.0, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.1, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.10, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.11, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.12, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.13, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.2, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.3, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.4, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.5, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.6, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.7, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.8, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.6.9, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.7.0, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.7.1, 2.1.2].
    - Can only install one of: doctrine/doctrine-bundle[1.7.2, 2.1.2].
    - Installation request for doctrine/doctrine-bundle (locked at 2.1.2) -> satisfiable by doctrine/doctrine-bundle[2.1.2].
`

Wie muss ich die composer.json modifizieren, damit es sich installieren lässt? Ich schätze es wird ein noconflict-Eintrag sein? Sorry, bin nich sooo fit was Composer angeht :-)

**Comment by cgpro** [comment]
Hi David,

vielen Dank für das schnelle Feedback! :-)

`composer require contao-bootstrap/bundle:~2.1.0 --no-update
composer update -o`

Damit hat es geklappt.

**Comment by yoyobo** [comment]
Hallo zusammen,
ich wurde gerade aus dem [Forum](https://community.contao.org/de/showthread.php?79759-Bootstrap-l%C3%A4sst-sich-nicht-installieren-c4-9-9&p=537786&viewfull=1#post537786) hierauf verwiesen. Ich nutze Contao in einem normalen Webhosting-Paket bei HostEurope. Das funktioniert dank des Cloud-Resolvers zum Glück bisher problemlos, allerdings habe ich keinen SSH-Zugang. Gibt es eine Möglichkeit, das Vorgehen über die GUI des Contao-Managers  auszulösen?
Danke und viele Grüße
yoyobo

**Comment by fritzmg** [comment]
As mentioned here and on the forum, you need to do a full package update in order to install this extension. If you use the Contao Manager, then you need to do the following steps:

1. Mark all packages to be upated.
2. Do **not** apply these changes!
3. Add the new package.
4. Now apply the changes.

**Comment by yoyobo** [comment]
Hi @fritzmg,

Thank you, it worked!

Best regards
yoyobo
