### ISSUE TITLE
PHP 8.0

### ISSUE THREAD

**Issue by scuben** [contao-bootstrap/core#36]
Existiert ein Plan die contao-bootstrap packages für PHP 8 zu veröffentlichen?

**Comment by BennyK80** [comment]
@dmolineus 
Über eine kurze Info wäre ich ebenfalls sehr dankbar.

**Comment by dmolineus** [comment]
Einen konkreten Plan gibt es nicht, wird aber sicherlich passieren, sobald ein Projekt dies entsprechend benötigt und refinanziert.

**Comment by dmolineus** [comment]
Aktuell ist die Erweiterung nicht Contao 4.13/PHP 8 kompatibel. Es wurde ein Fundraising gestartet um die Weiterentwicklung sicherzustellen. Mehr Informationen dazu unter https://contao-bootstrap.de/contao-4-13-kompatibilitaet.html

**Comment by dmolineus** [comment]
Der `develop` Branch ist nun PHP 8 kompatibel und kann getestet werden.
