### ISSUE TITLE
Contao >4.12 und Symfony 5.2 

### ISSUE THREAD

**Issue by HjueFricke** [contao-bootstrap/core#37]
Eine stolle Extension. Leider gibt es ab 4.12 Probleme:

Es gibt einen Fehler beim Eventdispatcher. Eventclass wurde geändert.  
Ab Symfony 5 ist sie Symfony\**Contracts**\EventDispatcher\Event;

Nach der (manuellen) Änderungen kommt dann der nächste Error:
Argument 1 passed to Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher::dispatch() must be an object, string given, called in /www/htdocs/w0175fba/hpvermittlung/vendor/contao-bootstrap/core/src/Listener/HookListener.php on line 76

Herzliche Grüße
Hjue

**Comment by dmolineus** [comment]
Seit Release 2.0.5 sind die Abhängigkeiten zu Symfony korrekt definiert. Es muss sichergestellt werden, dass mindestens `contao-bootsrap/core ^2.0.5` installiert wird.

https://github.com/contao-bootstrap/core/blob/f6b43157581a509feb4c8030293dc805613a3c31/composer.json#L26

Dies erzeugt dann ein Downgrade der Symfony-Pakete und hilft zumindest in Contao 4.12.

**Comment by dmolineus** [comment]
Aktuell ist die Erweiterung nicht Contao 4.13 kompatibel. Es wurde ein Fundraising gestartet um die Weiterentwicklung sicherzustellen. Mehr Informationen dazu unter https://contao-bootstrap.de/contao-4-13-kompatibilitaet.html

**Comment by dmolineus** [comment]
Der `develop` Branch ist nun Contao 4.13 kompatibel und kann getestet werden.

**Comment by Kahmoon** [comment]
Wenn du mir sagst was ich in der composer,json für develop einstellen muss, teste ich gerne die Tage mal.

**Comment by dmolineus** [comment]
Die Kompatibilität betrifft aktuell nur den Core. Weitere Komponenten folgen demnächst bzw. dann nach Fortschritt des Fundraisings. Für den Core kann man die zukünftige Version 2.1 anfordern `"contao-boostrap/core"; "^2.1@dev"`
