### ISSUE TITLE
Kompatibilität für Contao 4.13?

### ISSUE THREAD

**Issue by mwitzmann** [contao-bootstrap/core#38]
Vielen Dank für dieses tolle Bundle! Wann wird das Bundle für Contao 4.13 verfügbar sein?

**Comment by Kahmoon** [comment]
https://github.com/contao-bootstrap/grid/issues/46

Vermutlich hier die selbe Antwort :-)

**Comment by mwitzmann** [comment]
Vermutlich ja :)

**Comment by Songworks** [comment]
It's not compatible with Contao 4.13. We've tried an update and reinstall but it throws composer conflicts as contao-bootstrap has a few version requirements on dependencies (Symfony and the like) that conflict with newer version required by Contao 4.13. :(

**Comment by Kahmoon** [comment]
Sponsoring is possible: https://github.com/contao-bootstrap/grid/issues/46#issuecomment-1042812458

**Comment by dmolineus** [comment]
https://contao-bootstrap.de/contao-4-13-kompatibilitaet.html

**Comment by dmolineus** [comment]
Der `develop` Branch ist nun Contao 4.13 kompatibel und kann getestet werden.
