### ISSUE TITLE
Fehler beim Erstellen von Inhaltselement / Issue: creating content elements

### ISSUE THREAD

**Issue by martonos** [contao-bootstrap/core#7]
Unter Contao 3.4.5, bei Installation per Composer und in Verbindung mit Subcolumns kann es zu Problemen kommen. Beim erstellen von Inhaltselementen wird folgender Fehler ausgegeben:

```
Warning: Invalid argument supplied for foreach() in composer/vendor/contao-bootstrap/core/src/Contao/ContentElement/Wrapper/Helper.php on line 83
```

Lösung: unter systen/config/initconfig.php folgendes eintragen:

```
if (!Netzmacht\Bootstrap\Core\Bootstrap::getConfigVar('wrappers')) {
    Netzmacht\Bootstrap\Core\Bootstrap::setConfigVar('wrappers', array());
}
```

**Comment by dmolineus** [comment]
Fix got finally released in version 1.0.4.
