### ISSUE TITLE
Falsche Größe im Frontend bei Spaltensets

### ISSUE THREAD

**Issue by martonos** [contao-bootstrap/core#8]
Leider etwas schwer zu reproduzieren, beim ersten angelegten Spaltenset (50/50) wurde im Frontend col-lg-6 ausgeben, obwohl col-sm-6 definiert war. Beim zweiten Spaltenset und den darauffolgenden funktionierte es.

**Comment by dmolineus** [comment]
Fixed in https://github.com/contao-bootstrap/grid-editor/commit/8e5a8d3d9e2931eaca0a68c5f8f823cf834f4528
